---
 - name: install proxmox on nodes
   hosts: all

   tasks:
    - name: Ping host
      ping: ~
##
    - name: Add an Apt signing key to a specific keyring file
      apt_key:
        url: http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg
        keyring: /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
##
    - apt_repository:
       repo: deb http://download.proxmox.com/debian/pve stretch pve-no-subscription
       state: absent
       filename: pve-install-repo
    - apt_repository:
       repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
       state: present
       filename: pve-install-repo

    - apt_repository:
       repo: "{{ item }}"
       state: absent
      loop:
        - deb http://ftp.ru.debian.org/debian stretch main
        - deb http://mirror.yandex.ru/debian/ stretch main contrib non-free
        - deb-src http://mirror.yandex.ru/debian/ stretch main contrib non-free
        - deb http://download.proxmox.com/debian/corosync-3/ stretch main
        - deb http://download.proxmox.com/debian/ceph-luminous stretch main
    - apt_repository:
       repo: "{{ item }}"
       state: present
      loop:
        - deb http://ftp.ru.debian.org/debian buster main
        - deb http://mirror.yandex.ru/debian/ buster main contrib non-free
        - deb-src http://mirror.yandex.ru/debian/ buster main contrib non-free
    - name: userdel
      user:
         name: kvm
         state: absent
         remove: yes
##
    - name: Update apt packages
      apt:
        update_cache: yes
#        upgrade: dist
##  
    - name: Copy file with owner and permissions
      copy:
        src: ./etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

##
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - mc
        - ifenslave
        - bridge-utils
#        - pve-manager
#        - proxmox-ve
        - htop
        - tcpdump
        - ethtool
        - hdparm
        - ntp
        - net-tools

